package com.github.quillraven.fleks.plugin

import org.jetbrains.kotlin.GeneratedDeclarationKey
import org.jetbrains.kotlin.backend.common.extensions.IrGenerationExtension
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.backend.common.lower.DeclarationIrBuilder
import org.jetbrains.kotlin.cli.common.messages.CompilerMessageSeverity
import org.jetbrains.kotlin.cli.common.messages.MessageCollector
import org.jetbrains.kotlin.compiler.plugin.CompilerPluginRegistrar
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.jetbrains.kotlin.config.CommonConfigurationKeys
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.declarations.FirClassLikeDeclaration
import org.jetbrains.kotlin.fir.declarations.FirDeclarationOrigin.Plugin
import org.jetbrains.kotlin.fir.declarations.hasAnnotation
import org.jetbrains.kotlin.fir.declarations.utils.isCompanion
import org.jetbrains.kotlin.fir.extensions.FirDeclarationGenerationExtension
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrar
import org.jetbrains.kotlin.fir.extensions.FirExtensionRegistrarAdapter
import org.jetbrains.kotlin.fir.extensions.FirSupertypeGenerationExtension
import org.jetbrains.kotlin.fir.extensions.MemberGenerationContext
import org.jetbrains.kotlin.fir.extensions.NestedClassGenerationContext
import org.jetbrains.kotlin.fir.extensions.predicate.DeclarationPredicate
import org.jetbrains.kotlin.fir.plugin.createCompanionObject
import org.jetbrains.kotlin.fir.plugin.createDefaultPrivateConstructor
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.SymbolInternals
import org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirClassSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirConstructorSymbol
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.types.ConeKotlinType
import org.jetbrains.kotlin.fir.types.constructStarProjectedType
import org.jetbrains.kotlin.fir.types.constructType
import org.jetbrains.kotlin.ir.builders.irBlockBody
import org.jetbrains.kotlin.ir.builders.irDelegatingConstructorCall
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrDeclarationOrigin
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.companionObject
import org.jetbrains.kotlin.ir.util.constructors
import org.jetbrains.kotlin.ir.util.defaultType
import org.jetbrains.kotlin.ir.util.hasAnnotation
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.ir.visitors.acceptChildrenVoid
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name
import org.jetbrains.kotlin.name.SpecialNames

private val COMPONENT_ANNOTATION_CLASS_ID = ClassId.fromString("com/github/quillraven/fleks/FleksComponent")
private val FLEKS_COMPONENT_CLASS_ID = ClassId.fromString("com/github/quillraven/fleks/Component")
private val COMPONENT_TYPE_CLASS_ID = ClassId.fromString("com/github/quillraven/fleks/ComponentType")
private val COMPONENT_ANNOTATION_FQN = FqName("com.github.quillraven.fleks.FleksComponent")

/** Key that tags all declarations generated by this plugin — used to link FIR → IR. */
data object FleksPluginKey : GeneratedDeclarationKey()

class FleksSupertypeGenerationExtension(session: FirSession) : FirSupertypeGenerationExtension(session) {
    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(DeclarationPredicate.create { annotated(COMPONENT_ANNOTATION_FQN) })
    }

    override fun needTransformSupertypes(declaration: FirClassLikeDeclaration): Boolean =
        declaration.hasAnnotation(COMPONENT_ANNOTATION_CLASS_ID, session)

    override fun computeAdditionalSupertypes(
        classLikeDeclaration: FirClassLikeDeclaration,
        resolvedSupertypes: List<org.jetbrains.kotlin.fir.types.FirResolvedTypeRef>,
        typeResolver: TypeResolveService,
    ): List<ConeKotlinType> {
        val symbol = session.symbolProvider.getClassLikeSymbolByClassId(FLEKS_COMPONENT_CLASS_ID) ?: return emptyList()
        return listOf(symbol.constructType(isMarkedNullable = false))
    }
}

class FleksCompanionGenerationExtension(session: FirSession) : FirDeclarationGenerationExtension(session) {
    override fun FirDeclarationPredicateRegistrar.registerPredicates() {
        register(DeclarationPredicate.create { annotated(COMPONENT_ANNOTATION_FQN) })
    }

    private fun FirClassSymbol<*>.isComponentClass(): Boolean {
        if (this !is FirRegularClassSymbol) return false
        return hasAnnotation(COMPONENT_ANNOTATION_CLASS_ID, session)
    }

    @OptIn(SymbolInternals::class)
    override fun getNestedClassifiersNames(
        classSymbol: FirClassSymbol<*>,
        context: NestedClassGenerationContext,
    ): Set<Name> {
        if (!classSymbol.isComponentClass()) return emptySet()
        val hasCompanion = (classSymbol as? FirRegularClassSymbol)?.companionObjectSymbol != null
        return if (hasCompanion) emptySet() else setOf(SpecialNames.DEFAULT_NAME_FOR_COMPANION_OBJECT)
    }

    override fun generateNestedClassLikeDeclaration(
        owner: FirClassSymbol<*>,
        name: Name,
        context: NestedClassGenerationContext,
    ): FirClassLikeSymbol<*>? {
        if (name != SpecialNames.DEFAULT_NAME_FOR_COMPANION_OBJECT) return null
        if (!owner.isComponentClass()) return null

        val componentTypeSymbol = session.symbolProvider.getClassLikeSymbolByClassId(COMPONENT_TYPE_CLASS_ID) ?: return null
        val ownerType = owner.constructStarProjectedType(isMarkedNullable = false)
        val supertypeCone = componentTypeSymbol.constructType(arrayOf(ownerType), isMarkedNullable = false)

        return createCompanionObject(owner, FleksPluginKey) {
            superType(supertypeCone)
        }.symbol
    }

    override fun getCallableNamesForClass(
        classSymbol: FirClassSymbol<*>,
        context: MemberGenerationContext,
    ): Set<Name> {
        val isGeneratedCompanion = classSymbol.isCompanion && classSymbol.origin == Plugin(FleksPluginKey)
        return if (isGeneratedCompanion) setOf(SpecialNames.INIT) else emptySet()
    }

    override fun generateConstructors(context: MemberGenerationContext): List<FirConstructorSymbol> {
        val owner = context.owner
        if (!(owner.isCompanion && owner.origin == Plugin(FleksPluginKey))) return emptyList()
        return listOf(createDefaultPrivateConstructor(owner, FleksPluginKey).symbol)
    }
}

class FleksIrGenerationExtension(private val messageCollector: MessageCollector) : IrGenerationExtension {
    override fun generate(moduleFragment: IrModuleFragment, pluginContext: IrPluginContext) {
        moduleFragment.acceptChildrenVoid(FleksIrVisitor(pluginContext, messageCollector))
    }
}

@OptIn(UnsafeDuringIrConstructionAPI::class)
private class FleksIrVisitor(
    private val ctx: IrPluginContext,
    private val messageCollector: MessageCollector
) : IrVisitorVoid() {
    private val componentTypeSymbol by lazy {
        val symbol = ctx.finderForBuiltins().findClass(COMPONENT_TYPE_CLASS_ID)
        if (symbol == null) {
            messageCollector.report(
                CompilerMessageSeverity.ERROR,
                "Fleks Compiler Plugin: ComponentType not found on classpath — add fleks-runtime as a dependency."
            )
        }
        symbol
    }

    override fun visitElement(element: org.jetbrains.kotlin.ir.IrElement) =
        element.acceptChildrenVoid(this)

    override fun visitClass(declaration: IrClass) {
        declaration.acceptChildrenVoid(this)

        if (!declaration.hasAnnotation(COMPONENT_ANNOTATION_FQN)) return

        val companion = declaration.companionObject() ?: return
        // Only fill in the body of companions we generated via FIR
        if (companion.origin !is IrDeclarationOrigin.GeneratedByPlugin) return

        val ctor = companion.constructors.singleOrNull { it.isPrimary } ?: return
        if (ctor.body != null) return

        // if targetSymbol == null then an error was already reported using the MessageCollector
        val targetSymbol = componentTypeSymbol ?: return
        val superCtor = targetSymbol.owner.constructors.singleOrNull { it.isPrimary } ?: return

        ctor.body = DeclarationIrBuilder(ctx, ctor.symbol).irBlockBody {
            +irDelegatingConstructorCall(superCtor).also { call ->
                call.typeArguments[0] = declaration.defaultType
            }
        }
    }
}

class FleksExtensionRegistrar : FirExtensionRegistrar() {
    override fun ExtensionRegistrarContext.configurePlugin() {
        +::FleksSupertypeGenerationExtension
        +::FleksCompanionGenerationExtension
    }
}

@OptIn(ExperimentalCompilerApi::class)
class FleksCompilerPlugin : CompilerPluginRegistrar() {
    override val pluginId: String = "com.github.quillraven.fleks.compiler-plugin"
    override val supportsK2: Boolean = true

    override fun ExtensionStorage.registerExtensions(configuration: CompilerConfiguration) {
        val messageCollector = configuration[CommonConfigurationKeys.MESSAGE_COLLECTOR_KEY, MessageCollector.NONE]
        FirExtensionRegistrarAdapter.registerExtension(FleksExtensionRegistrar())
        IrGenerationExtension.registerExtension(FleksIrGenerationExtension(messageCollector))
    }
}
